# Generated by Django 5.0.6 on 2024-05-26 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Last name"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=255, verbose_name="Phone Number"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_diagnostic",
                    models.CharField(max_length=255, verbose_name="Date of diagnostic"),
                ),
                ("diagnostic", models.TextField(verbose_name="Diagnostic")),
                ("note", models.CharField(max_length=255, verbose_name="Note")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Segmentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_segmentation",
                    models.CharField(
                        max_length=255, verbose_name="Date of segmentation"
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(upload_to="", verbose_name="Original Image"),
                ),
                (
                    "segmented_image",
                    models.ImageField(upload_to="", verbose_name="Segmented Image"),
                ),
                ("note", models.CharField(max_length=255, verbose_name="Note")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
        ),
    ]
